{{- if (eq true .Values.global.externalServicesMock.tenantDependenciesConfig.manage) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.global.tenantFetcher.dependenciesConfig.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
stringData:
  keyConfig: |
    {
        "eu-1": "{\n \"xsappname\": \"xsappname1\", \"clientid\": \"clientid-1\", \"certificate\": \"client-cert-1\", \"key\": \"client-cert-key-1\", \"url\": \"http://token-url\", \"uri\": \"http://destination-service\"\n}",
        "eu-2": "{\n \"xsappname\": \"xsappname2\", \"clientid\": \"clientid-2\", \"certificate\": \"client-cert-2\", \"key\": \"client-cert-key-2\", \"url\": \"http://token-url\", \"uri\": \"http://destination-service\"\n}"
    }
{{- end }}
