{{- if (eq true .Values.global.externalServicesMock.tenantDependenciesConfig.manage) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.global.tenantFetcher.dependenciesConfig.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
stringData:
  keyConfig: |
    {
    "eu-1": "{\n \"credentials\": {\n \"xsappname\": \"xsappname1\"\n}\n}",
    "eu-2": "{\n \"credentials\": {\n \"xsappname\": \"xsappname1\"\n}\n}"
    }
{{- end }}
