// Code generated by mockery. DO NOT EDIT.

package automock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DestinationSyncer is an autogenerated mock type for the DestinationSyncer type
type DestinationSyncer struct {
	mock.Mock
}

// SyncSubaccountDestinations provides a mock function with given fields: ctx, subaccountID
func (_m *DestinationSyncer) SyncSubaccountDestinations(ctx context.Context, subaccountID string) error {
	ret := _m.Called(ctx, subaccountID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, subaccountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDestinationSyncer interface {
	mock.TestingT
	Cleanup(func())
}

// NewDestinationSyncer creates a new instance of DestinationSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDestinationSyncer(t mockConstructorTestingTNewDestinationSyncer) *DestinationSyncer {
	mock := &DestinationSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
