// Code generated by mockery. DO NOT EDIT.

package automock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DestinationResyncer is an autogenerated mock type for the DestinationResyncer type
type DestinationResyncer struct {
	mock.Mock
}

// FetchDestinationsOnDemand provides a mock function with given fields: ctx, subaccountID
func (_m *DestinationResyncer) FetchDestinationsOnDemand(ctx context.Context, subaccountID string) error {
	ret := _m.Called(ctx, subaccountID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, subaccountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDestinationResyncer interface {
	mock.TestingT
	Cleanup(func())
}

// NewDestinationResyncer creates a new instance of DestinationResyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDestinationResyncer(t mockConstructorTestingTNewDestinationResyncer) *DestinationResyncer {
	mock := &DestinationResyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
