// Code generated by mockery. DO NOT EDIT.

package automock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-incubator/compass/components/director/internal/model"
)

// SubscribedTenantFetcher is an autogenerated mock type for the SubscribedTenantFetcher type
type SubscribedTenantFetcher struct {
	mock.Mock
}

// GetBySubscribedRuntimes provides a mock function with given fields: ctx
func (_m *SubscribedTenantFetcher) GetBySubscribedRuntimes(ctx context.Context) ([]*model.BusinessTenantMapping, error) {
	ret := _m.Called(ctx)

	var r0 []*model.BusinessTenantMapping
	if rf, ok := ret.Get(0).(func(context.Context) []*model.BusinessTenantMapping); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.BusinessTenantMapping)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSubscribedTenantFetcher interface {
	mock.TestingT
	Cleanup(func())
}

// NewSubscribedTenantFetcher creates a new instance of SubscribedTenantFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSubscribedTenantFetcher(t mockConstructorTestingTNewSubscribedTenantFetcher) *SubscribedTenantFetcher {
	mock := &SubscribedTenantFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
